# Generated by Django 5.0.7 on 2024-09-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=100)),
                ('book_name', models.CharField(max_length=255)),
                ('book_price', models.CharField(max_length=255)),
                ('book_author', models.CharField(default='Author', max_length=255)),
                ('book_image', models.ImageField(blank='True', null='True', upload_to='images/')),
                ('book_details', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'book_store',
            },
        ),
    ]
