# Generated by Django 5.0.7 on 2024-09-27 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_id',
        ),
    ]
