# Generated by Django 5.0.7 on 2024-10-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0004_alter_books_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'login_table',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_id', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'register_table',
            },
        ),
    ]
