# Generated by Django 5.0.7 on 2024-10-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0005_login_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='full_name',
            field=models.CharField(default='ABC', max_length=255),
        ),
    ]
